package vvgbankomat;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class biranjeIznosa implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public biranjeIznosa() {
    }

}