package vvgbankomat;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class biranjeIznosa implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "idBiraniIznos")
   private java.lang.Integer idBiraniIznos;
   @org.kie.api.definition.type.Label(value = "moguciIznos")
   private java.lang.String moguciIznos;

   public biranjeIznosa()
   {
   }

   public java.lang.Integer getIdBiraniIznos()
   {
      return this.idBiraniIznos;
   }

   public void setIdBiraniIznos(java.lang.Integer idBiraniIznos)
   {
      this.idBiraniIznos = idBiraniIznos;
   }

   public java.lang.String getMoguciIznos()
   {
      return this.moguciIznos;
   }

   public void setMoguciIznos(java.lang.String moguciIznos)
   {
      this.moguciIznos = moguciIznos;
   }

   public biranjeIznosa(java.lang.Integer idBiraniIznos,
         java.lang.String moguciIznos)
   {
      this.idBiraniIznos = idBiraniIznos;
      this.moguciIznos = moguciIznos;
   }

}