package vvgbankomat;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class izborListicaDat implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public izborListicaDat() {
    }

}