package vvgbankomat;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("izborBonaDat")
public class izborBonaDat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("IzborBona")
   private Integer izborBona;

   public izborBonaDat()
   {
   }

   public java.lang.Integer getIzborBona()
   {
      return this.izborBona;
   }

   public void setIzborBona(java.lang.Integer izborBona)
   {
      this.izborBona = izborBona;
   }

   public izborBonaDat(java.lang.Integer izborBona)
   {
      this.izborBona = izborBona;
   }

}