package vvgbankomat;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("izborListicaDat")
public class izborListicaDat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Da")
   private java.lang.Boolean da;
   @org.kie.api.definition.type.Label("Ne")
   private java.lang.Boolean ne;

   @org.kie.api.definition.type.Label(value = "izborListicaDaNe")
   private java.lang.String izborListicaDaNe;

   public izborListicaDat()
   {
   }

   public java.lang.Boolean getDa()
   {
      return this.da;
   }

   public void setDa(java.lang.Boolean da)
   {
      this.da = da;
   }

   public java.lang.Boolean getNe()
   {
      return this.ne;
   }

   public void setNe(java.lang.Boolean ne)
   {
      this.ne = ne;
   }

   public java.lang.String getIzborListicaDaNe()
   {
      return this.izborListicaDaNe;
   }

   public void setIzborListicaDaNe(java.lang.String izborListicaDaNe)
   {
      this.izborListicaDaNe = izborListicaDaNe;
   }

   public izborListicaDat(java.lang.Boolean da, java.lang.Boolean ne,
         java.lang.String izborListicaDaNe)
   {
      this.da = da;
      this.ne = ne;
      this.izborListicaDaNe = izborListicaDaNe;
   }

}