package vvgbankomat;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class izborBonaDat implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public izborBonaDat() {
    }

}