package vvgbankomat;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("izborIznosaDat")
public class izborIznosaDat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("IzabranIznos")
   private String izabranIznos;

   public izborIznosaDat()
   {
   }

   public java.lang.String getIzabranIznos()
   {
      return this.izabranIznos;
   }

   public void setIzabranIznos(java.lang.String izabranIznos)
   {
      this.izabranIznos = izabranIznos;
   }

   public izborIznosaDat(java.lang.String izabranIznos)
   {
      this.izabranIznos = izabranIznos;
   }

}