package vvgbankomat;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class izborIznosaDat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "izborIznosa")
   private java.lang.String izborIznosa;
   @org.kie.api.definition.type.Label(value = "idIznosa")
   private java.lang.Integer idIznosa;

   public izborIznosaDat()
   {
   }

   public java.lang.String getIzborIznosa()
   {
      return this.izborIznosa;
   }

   public void setIzborIznosa(java.lang.String izborIznosa)
   {
      this.izborIznosa = izborIznosa;
   }

   public java.lang.Integer getIdIznosa()
   {
      return this.idIznosa;
   }

   public void setIdIznosa(java.lang.Integer idIznosa)
   {
      this.idIznosa = idIznosa;
   }

   public izborIznosaDat(java.lang.String izborIznosa,
         java.lang.Integer idIznosa)
   {
      this.izborIznosa = izborIznosa;
      this.idIznosa = idIznosa;
   }

}