package vvgbankomat;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("izborIznosaDat")
public class izborIznosaDat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public izborIznosaDat()
   {
   }

}