package vvgbankomat;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("izborTransakcijeDat")
public class izborTransakcijeDat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Izbor")
   private String izbor;

   public izborTransakcijeDat()
   {
   }

   public java.lang.String getIzbor()
   {
      return this.izbor;
   }

   public void setIzbor(java.lang.String izbor)
   {
      this.izbor = izbor;
   }

   public izborTransakcijeDat(java.lang.String izbor)
   {
      this.izbor = izbor;
   }

}