package vvgbankomat;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("korisnikDat")
public class korisnikDat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Ime")
   private java.lang.String ime;
   @org.kie.api.definition.type.Label("Prezime")
   private java.lang.String prezime;
   @org.kie.api.definition.type.Label("Oib")
   private java.lang.String oib;
   @org.kie.api.definition.type.Label("StanjeRacuna")
   private java.lang.Long stanje;
   @org.kie.api.definition.type.Label("Pin")
   private Short pin;

   public korisnikDat()
   {
   }

   public java.lang.String getIme()
   {
      return this.ime;
   }

   public void setIme(java.lang.String ime)
   {
      this.ime = ime;
   }

   public java.lang.String getPrezime()
   {
      return this.prezime;
   }

   public void setPrezime(java.lang.String prezime)
   {
      this.prezime = prezime;
   }

   public java.lang.String getOib()
   {
      return this.oib;
   }

   public void setOib(java.lang.String oib)
   {
      this.oib = oib;
   }

   public java.lang.Long getStanje()
   {
      return this.stanje;
   }

   public void setStanje(java.lang.Long stanje)
   {
      this.stanje = stanje;
   }

   public java.lang.Short getPin()
   {
      return this.pin;
   }

   public void setPin(java.lang.Short pin)
   {
      this.pin = pin;
   }

   public korisnikDat(java.lang.String ime, java.lang.String prezime,
         java.lang.String oib, java.lang.Long stanje, java.lang.Short pin)
   {
      this.ime = ime;
      this.prezime = prezime;
      this.oib = oib;
      this.stanje = stanje;
      this.pin = pin;
   }

}