package vvgbankomat;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("unosPinaData")
public class unosPinaData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Pin")
   private java.lang.String pin;

   public unosPinaData()
   {
   }

   public java.lang.String getPin()
   {
      return this.pin;
   }

   public void setPin(java.lang.String pin)
   {
      this.pin = pin;
   }

   public unosPinaData(java.lang.String pin)
   {
      this.pin = pin;
   }

}