package vvgbankomat;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("vrijednostBona")
public class vrijednostBona implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "VrijednostBona")
   private java.lang.Integer vrijednostBona;

   public vrijednostBona()
   {
   }

   public java.lang.Integer getVrijednostBona()
   {
      return this.vrijednostBona;
   }

   public void setVrijednostBona(java.lang.Integer vrijednostBona)
   {
      this.vrijednostBona = vrijednostBona;
   }

   public vrijednostBona(java.lang.Integer vrijednostBona)
   {
      this.vrijednostBona = vrijednostBona;
   }

}